name: Terraform Plan

on:
  push:
    branches: 
      - test

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    env:
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
    

